#!/usr/bin/env bash
 
. $(dirname $(realpath -s $0))/functions

install_if_missing gnome gnome-extra gnome-themes-extra

sudo systemctl enable gdm

# gnome extension manager
flatpak install flathub com.mattjakeman.ExtensionManager
