#!/usr/bin/env bash

. $(dirname $(realpath -s $0))/functions

PACKAGES="
arch-install-scripts
exfat-utils
dosfstools
cmake
fish
less
man-pages
man-db
exa
bat
lsb-release
usbutils
git
lazygit
openssh
fastfetch
neovim
mesa
xf86-video-amdgpu
vulkan-radeon
mpv
otf-font-awesome
ttf-jetbrains-mono
ttf-jetbrains-mono-nerd
ttf-ubuntu-font-family
adobe-source-code-pro-fonts
rclone
wl-clipboard
flatpak
"
install_if_missing $PACKAGES
