#!/usr/bin/env bash

. $(dirname $(realpath -s $0))/modules/functions

modules_path() { 
    echo "$(this_file_path)/modules" 
}

set -e

define OPTIONS <<'OPTIONS_END'
Options
-b  install brave browser
-c  install cups and printer drivers
-f  copy filofem-install.sh script in /home/filofem
-g  install gnome and enable gdm display manager
-n  apply gnome-settings
-o  install google chrome
-p  install jotix's packages
-s  install steam
-u  copy udev-rules to /etc/udev/rules.d
-v  install libvirt and VM manager
-y  install hyprland and tools
-h  display this message
OPTIONS_END

[[ $@ == "" ]] && echo "$OPTIONS"

OPTSTRING=":bcfgnopsuvyh"

while getopts ${OPTSTRING} opt; do
    case ${opt} in
        b)
            $(modules_path)/brave-browser-install
            ;;
        c)
            $(modules_path)/cups-install
            ;;
        f)
            [[ $HOSTNAME == "ffm-arch" ]] && $(modules_path)/filofem-install-maker
            ;;
        g)
            $(modules_path)/gnome-install
            ;;
        n)
            $(modules_path)/gnome-settings
            ;;
        o)
            $(modules_path)/google-chrome-install
            ;;
        p)
            $(modules_path)/packages-install
            ;;
        s)
            $(modules_path)/steam-install
            ;;
        u)
            $(modules_path)/udev-rules-install
            ;;
        v)
            $(modules_path)/virt-install
            ;;
        y)
            $(modules_path)/hyprland-install
            ;;
        *)
            echo "$OPTIONS"
            ;;
    esac
done
